Repository wecode-bootcamp-korea/50-3rd-mayfly-frontend, pull requests merged in 2023-11, with the labels that each got.

#8 이벤트 기획자 마이 페이지 UI 초안
  src/pages/MyPageEvent/MyPageEvent.js
  src/pages/MyPageEvent/MyPageEvent.scss
Labels: 멘토 리뷰 요청

#7 유저 마이페이지 UI 초안
  src/pages/MyPageUser/MyPageUser.js
  src/pages/MyPageUser/MyPageUser.scss
Labels: 멘토 리뷰 요청

#2 리스트 페이지 UI 초안
  src/pages/List/List.js
  src/pages/List/List.scss
Labels: 멘토 리뷰 요청

#1 상세페이지 초안
  package-lock.json
  package.json
  public/index.html
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
Labels: 멘토 리뷰 요청

#3 [50기 최민지] Design : Nav UI 수정 및 피드백 반영
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/Sidebar.js
  src/components/Nav/Sidebar.scss
  src/components/Nav/navImg/category.png
  src/components/Nav/navImg/heart.png
  src/components/Nav/navImg/logo.png
  src/components/Nav/navImg/user.png
Labels: 멘토 리뷰 요청

#9 소셜로그인 페이지 css
  .gitignore
  public/images/kakao_login_large_narrow.png
  public/images/kakao_login_large_wide.png
  public/images/kakao_login_medium_narrow.png
  public/images/kakao_login_medium_wide.png
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 완료

#4 [50기 최민지] Design : Main UI 초안
  public/data/mainMockData.json
  src/Router.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청

#11 [50기 최민지] Feat : 카테고리 기능 추가
  public/data/dummy.json
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/Sidebar.js
  src/components/Nav/Sidebar.scss
  src/components/Nav/components/CategoryList.js
  src/components/Nav/components/CategoryList.scss
  src/components/Nav/components/Sidebar.js
  src/components/Nav/components/Sidebar.scss
  src/config.js
Labels: 멘토 리뷰 요청

#12 [50기 최민지] Fix : 컨플릭트 해결 및 merge 후 추가기능 구현 예정
  public/data/listMockData.json
  src/config.js
  src/pages/List/List.js
  src/pages/List/List.scss
  src/pages/List/components/Search.js
  src/pages/List/components/Search.scss
  src/pages/List/components/Sort.js
  src/pages/List/components/Sort.scss
  src/pages/List/components/SubCategories.js
  src/pages/List/components/SubCategories.scss
Labels: 멘토 리뷰 요청

#10 로그인 리다이렉트 페이지 완성 / 대기화면 스피너 추가
  package-lock.json
  package.json
  src/Router.js
  src/components/Spinner/Spinner.js
  src/components/Spinner/Spinner.scss
  src/pages/Login/KAKAOevent.js
  src/pages/Login/KAKAOuser.js
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청, 완료

#14 관리자 로그인 페이지 완성
  src/Router.js
  src/pages/AdminLogin/AdminLogin.js
  src/pages/Login/KAKAOevent.js
  src/pages/Login/KAKAOuser.js
Labels: 완료

#18 Fix: 로그인 API연결 부분 변경
  src/pages/Login/KAKAOevent.js
  src/pages/Login/KAKAOuser.js
Labels: 멘토 리뷰 요청, 완료

#15 크레딧 충전 페이지 완료
  public/images/payment_icon_yellow_large.png
  src/Router.js
  src/pages/AdminLogin/AdminLogin.js
  src/pages/Credit/Credit.js
  src/pages/Credit/Credit.scss
  src/pages/Credit/KAKAOcredit.js
  src/pages/Credit/toss임시.png
Labels: 완료

#16 [50기 최민지] Feat : admin, user의 구분, 다른 사이드바 표시 구현
  src/components/Nav/Nav.js
  src/components/Nav/components/CategoryList.js
  src/components/Nav/components/Sidebar.js
  src/components/Nav/components/Sidebar.scss
  src/components/Nav/components/UserSideBar.js
  src/components/Nav/components/UserSideBar.scss
  src/config.js
  src/pages/List/List.js
  src/pages/List/List.scss
  src/pages/List/components/Search.js
  src/pages/List/components/Search.scss
  src/pages/List/components/Sort.js
  src/pages/List/components/SubCategories.js
  src/pages/Login/KAKAOevent.js
  src/pages/Login/KAKAOuser.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#13 Feat : 메인 페이지 탭 완성
  package-lock.json
  package.json
  src/components/Credit/Credit.js
  src/components/Credit/Credit.scss
  src/components/Profile/Profile.js
  src/components/Profile/Profile.scss
  src/components/Reservation/Reservation.js
  src/components/Reservation/Reservation.scss
  src/components/WishList/WishList.js
  src/components/WishList/WishList.scss
  src/pages/MyPageUser/MyPageUser.js
  src/pages/MyPageUser/MyPageUser.scss
Labels: 멘토 리뷰 요청

#17 [50기 최민지] Feat : main 페이지 기능 구현
  package-lock.json
  package.json
  public/data/mainMockData.json
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/Timer.js
  src/pages/Main/components/Timer.scss
Labels: 멘토 리뷰 요청

#19 관리자 페이지 - 필수기능 구현 완료
  package-lock.json
  src/Router.js
  src/components/Pagination/Pagination.js
  src/components/Pagination/Pagination.scss
  src/pages/Admin/Admin.js
  src/pages/Admin/Admin.scss
  src/pages/Admin/components/Adjustment.js
  src/pages/Admin/components/ClassList.js
  src/pages/Admin/components/ClassList.scss
  src/pages/Admin/components/HostList.js
  src/pages/Admin/components/HostList.scss
  src/pages/Admin/components/Modal.js
  src/pages/Admin/components/Modal.scss
  src/pages/Admin/components/UserList.js
  src/pages/Admin/components/UserList.scss
  src/pages/AdminLogin/AdminLogin.js
Labels: 완료

#20 Feat: 상세 페이지 기능 구현
  package-lock.json
  package.json
  src/components/CalendarApp/CalendarApp.js
  src/components/CalendarApp/CalendarApp.scss
  src/components/Refund/Refund.js
  src/components/Refund/Refund.scss
  src/components/ScheduleList/ScheduleList.js
  src/pages/Detail/Chat.js
  src/pages/Detail/Chat.scss
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
Labels: 멘토 리뷰 요청

#24 Fix : 일부 UI 수정 및 Nav fetch 코드 수정
  package-lock.json
  src/components/Carousel/Carousel.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/components/Nav/components/UserSideBar.js
  src/components/Nav/components/UserSideBar.scss
  src/components/Profile/Profile.js
  src/config.js
  src/pages/List/List.scss
  src/pages/List/components/SubCategories.js
  src/pages/List/components/SubCategories.scss
  src/pages/Login/KAKAOevent.js
  src/pages/Login/KAKAOuser.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/components/Timer.js
  src/pages/Main/components/Timer.scss
  src/pages/Main/mainIcon/bestIcon.png
  src/pages/Main/mainIcon/newClass.png
  src/pages/Main/mainIcon/upcomming.png
Labels: 멘토 리뷰 요청
